-- Membuat tabel 'courses' untuk menyimpan data kursus
CREATE TABLE courses (                           -- Nama tabel: courses
  name VARCHAR(255) NOT NULL,                    -- Kolom nama kursus, wajib diisi
  description TEXT,                              -- Kolom deskripsi, boleh null
  duration DEC(4, 2) NOT NULL                    -- Lama durasi (mis. 12.50), 4 digit total, 2 desimal, wajib
);

-- ---------------------------------------------------------------

-- Contoh perintah drop tabel (TIDAK DIEKSEKUSI di sini)
-- drop table 

-- Membuat tabel 'emergency_contacts' untuk kontak darurat pegawai
CREATE TABLE emergency_contacts (
  id INT PRIMARY KEY,                            -- Primary key (unik)
  first_name VARCHAR(255) NOT NULL,              -- Nama depan, wajib
  last_name VARCHAR(255) NOT NULL,               -- Nama belakang, wajib
  relationship VARCHAR(50) NOT NULL,             -- Hubungan (ayah/ibu/teman), wajib
  employee_id INT NOT NULL                       -- FK ke karyawan (butuh tabel employees), wajib
);
-- Catatan: Untuk foreign key sebenarnya perlu constraint FK eksplisit ke tabel 'employees'.

-- ---------------------------------------------------------------

-- Contoh penggunaan kolom IDENTITAS (auto-numbering) versi 1
CREATE TABLE ranks (
  rank_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  -- Kolom auto-increment; nilai selalu di‐generate DB
  rank_name CHAR NOT NULL                                 -- Nama pangkat; tipe CHAR (panjang tetap)
);

INSERT INTO ranks (rank_name) VALUES ('A');               -- Menambah baris; DB mengisi rank_id otomatis

SELECT * FROM ranks;                                      -- Mengecek isi tabel

INSERT INTO ranks (rank_id, rank_name) VALUES (2, 'B');   -- GAGAL pada "ALWAYS AS IDENTITY" (tidak boleh set rank_id)

-- ---------------------------------------------------------------

-- Versi 2 IDENTITAS: boleh set manual jika perlu
CREATE TABLE ranks (
  rank_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- DB mengisi default, tapi boleh override manual
  rank_name CHAR NOT NULL
);

INSERT INTO ranks (rank_name) VALUES ('A');               -- rank_id diisi otomatis

INSERT INTO ranks (rank_id, rank_name) VALUES (2, 'B');   -- Diperbolehkan (override nilai identity)

SELECT
  rank_id,
  rank_name
FROM
  ranks;

-- Catatan penting:
-- Dua CREATE TABLE dengan nama sama ('ranks') tidak bisa dieksekusi berurutan tanpa DROP TABLE ranks.
-- Blok di atas adalah dua skenario alternatif, pilih salah satu sesuai kebutuhan.

-- ---------------------------------------------------------------

-- ALTER TABLE: bentuk umum (TEMPLATE, bukan perintah nyata)
ALTER TABLE table_name
action;                                                   -- Placeholder: ganti 'action' dengan operasi nyata

-- Membuat tabel 'travel_requests' untuk permintaan perjalanan dinas
CREATE TABLE travel_requests (
  request_id INT,                                         -- Akan menjadi PK nanti
  employee_id INT,                                        -- Akan menjadi FK ke 'employees'
  destination VARCHAR(255) NOT NULL,                      -- Tujuan, wajib
  end_date DATE,                                          -- Tanggal akhir
  purpose TEXT,                                           -- Tujuan perjalanan (akan diubah tipe)
  status VARCHAR(20),                                     -- Status approval (akan di-rename)
  note TEXT                                               -- Catatan tambahan
);

-- TEMPLATE menambah kolom (perhatikan ejaan 'column')
ALTER TABLE table_name
ADD colum_name datatype constraint;                       -- Salah eja: seharusnya 'column_name'

-- Menambah kolom start_date yang wajib diisi
ALTER TABLE travel_requests
ADD COLUMN start_date DATE NOT NULL;

-- TEMPLATE mengubah tipe kolom (dialek SQL bisa berbeda)
ALTER TABLE table_name
ALTER COLUMN column_name SET datatype;

-- Mengubah tipe kolom purpose menjadi VARCHAR(255)
ALTER TABLE travel_requests
ALTER COLUMN purpose
SET DATA TYPE VARCHAR(255);                               -- Di beberapa DBMS: USING CAST(purpose AS VARCHAR(255))

-- TEMPLATE rename kolom
ALTER TABLE table_name
RENAME COLUMN column_name TO new_name;

-- Mengganti nama kolom 'status' menjadi 'approval_status'
ALTER TABLE travel_requests
RENAME COLUMN status TO approval_status;

-- Menambah CHECK constraint: end_date harus >= start_date
ALTER TABLE travel_requests
ADD CONSTRAINT check_dates 
CHECK(end_date >= start_date);

-- Menetapkan primary key pada request_id
ALTER TABLE travel_requests
ADD PRIMARY KEY (request_id);

-- Menambahkan foreign key ke tabel employees.employee_id
ALTER TABLE travel_requests
ADD CONSTRAINT fk_employee 
FOREIGN KEY (employee_id) 
REFERENCES employees (employee_id);                       -- Syarat: tabel 'employees' sudah ada

-- Mengganti nama tabel 'travel_requests' menjadi 'requests'
ALTER TABLE travel_requests
RENAME TO requests;

-- ---------------------------------------------------------------

-- Contoh NOT NULL constraint
CREATE TABLE candidates (
  first_name VARCHAR(255) NOT NULL,                       -- Wajib
  last_name  VARCHAR(255) NOT NULL,                       -- Wajib
  email      VARCHAR(512) NOT NULL,                       -- Wajib
  phone      VARCHAR(25)  NOT NULL                        -- Wajib
);

-- Contoh INSERT yang akan GAGAL karena email/phone NULL
INSERT INTO candidates (first_name, last_name, email, phone)
VALUES ('John', 'Doe', NULL, NULL);                       -- Pelanggaran NOT NULL

-- Contoh INSERT yang valid
INSERT INTO candidates (first_name, last_name, email, phone)
VALUES ('John','Doe','john.doe@gmail.com','(408)-111-2222');

-- TEMPLATE update nilai NULL menjadi non-NULL
UPDATE table_name
SET column_name = non_null_value
WHERE column_name IS NULL;

-- TEMPLATE ubah definisi kolom menjadi NOT NULL (dialek bisa berbeda)
ALTER TABLE table_name
MODIFY column_name data_type NOT NULL;                    -- MySQL/Oracle: MODIFY; PostgreSQL: ALTER COLUMN ... SET NOT NULL

-- ---------------------------------------------------------------

-- Membuat tabel 'interviews' dengan kolom wajib
CREATE TABLE interviews (
  candidate_id INT NOT NULL,                              -- Wajib, idealnya FK ke candidates
  hiring_manager VARCHAR(255) NOT NULL,                   -- Wajib
  interview_date TIMESTAMP                                -- Awalnya boleh NULL
);

-- Mengubah interview_date menjadi NOT NULL (dialek bergantung DBMS)
ALTER TABLE interviews 
MODIFY interview_date TIMESTAMP NOT NULL;                 -- MySQL/Oracle: MODIFY; PostgreSQL: ALTER COLUMN ... SET NOT NULL

